language: java
jdk:
  - oraclejdk8
before_script:
  - cp ./.travis/settings.xml ${HOME}/.m2/settings.xml
  - mvn -q -U install -DskipTests=true
script:
  - mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)