language: java
jdk:
  - oraclejdk8
before_install:
  - cp ./.travis/settings.xml ${HOME}/.m2/settings.xml
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify
after_success:
  - bash <(curl -s https://codecov.io/bash)